### PR TITLE
#165273585 Add search filtering functionality

### PR DESCRIPTION
**Pull request by kalsmic**
#### What does this PR do?
- Add Search Functionality and Custom filtering based on parameters.

#### Description of the task to be completed?
Add unit tests for search filtering functionality

#### How should this be manually tested?
Provide different search parameters in the URL for retrieving articles. Available parameters. include author, title and tags.
sample URL formats
- `GET /api/articles/?author=bison`
- `GET /api/articles/?title=How to do TDD`
- `GET /api/articles/?tag=python`
- `GET /api/articles/?author=bison&&tag=python`
- `GET /api/articles/?search=anything`

#### What are the relevant pivotal tracker stories?
[#165273585](https://www.pivotaltracker.com/story/show/165273585)

### CODE REVIEW

**Review by llwasampijja — CHANGES_REQUESTED** [review]
Nice work @kalsmic filter by the title is well implemented as a user can search by title regardless of the case of the search query. It would be great if even filter by tag, author as well as author & tag also had the same functionality.
In addition to that, I would also be great if a user is provided is a way to do a search outside the search options you have implemented. For example, if a user wants to just search for a word, and he/she doesn't mind if that keyword is in the title, author's username or tag. You can reach me if you need any assistance in implementing this!
All in all, great work,
Jah Bless, Selah!

**Comment by kalsmic** [comment]
> Nice work @kalsmic filter by the title is well implemented as a user can search by title regardless of the case of the search query. It would be great if even filter by tag, author as well as author & tag also had the same functionality.
> In addition to that, I would also be great if a user is provided is a way to do a search outside the search options you have implemented. For example, if a user wants to just search for a word, and he/she doesn't mind if that keyword is in the title, author's username or tag. You can reach me if you need any assistance in implementing this!
> All in all, great work,
> Jah Bless, Selah!

Let us work on this @llwasampijja, thanks for the feedback. We are going to add a custom search filter.

**Comment by kalsmic** [comment]
> > Nice work @kalsmic filter by the title is well implemented as a user can search by title regardless of the case of the search query. It would be great if even filter by tag, author as well as author & tag also had the same functionality.
> > In addition to that, I would also be great if a user is provided is a way to do a search outside the search options you have implemented. For example, if a user wants to just search for a word, and he/she doesn't mind if that keyword is in the title, author's username or tag. You can reach me if you need any assistance in implementing this!
> > All in all, great work,
> > Jah Bless, Selah!
> 
> Let us work on this @llwasampijja, thanks for the feedback. We are going to add a custom search filter.

@llwasampijja, changes have been implemented.

**Review by llwasampijja — APPROVED** [review]

**Review by JamesMudidi — APPROVED** [review]
Just tested the custom search and it works great. Thanks for removing the case sensitivity from the author and tags

**Review by nadralia — APPROVED** [review]

**Pull request merged**
