### PR TITLE
#165273588  User can create, read and delete Bookmarks

### PR DESCRIPTION
**Pull request by kalsmic**
#### What does this PR do?
This pull request enables a user to create, read and delete bookmarked articles.

#### Description of tasks to be completed?
- Add unit test for creating, getting and deleting bookmarks
- Add functionality to:-
  - Add article to Bookmark
  - View bookmarked articles
  - Delete a bookmark

#### Any background context you want to provide?

- I modified the permission to the Articles views to 'isAuthenticatedOrReadOnly` so that unauthenticated users can read the articles.
- Details of the bookmark endpoints and request body.

##### Bookmark / Un-bookmark an article
`POST /api/articles/:slug/bookmark/`

Authentication required, returns the created Bookmark
##### Get Bookmarks

`GET /api/articles/:slug/bookmarks/`

Authentication required, returns multiple bookmarks

#### What are the relevant pivotal tracker stories
[#165273588](https://www.pivotaltracker.com/story/show/165273588)

### CODE REVIEW

**Review by bisonlou — CHANGES_REQUESTED** [review]
This is good work @kalsmic. Though I noticed you have 3 endpoints - bookmarking an article, getting bookmarks, and deleting a bookmark. However, I think you can toggle bookmarking on and off using the same endpoint.

**Review by ZackAtama — CHANGES_REQUESTED** [review]
Awesome work @kalsmic, the logic is great, however, I believe it's better to have no request body. i.e let everything be in the url, e.g `api/articles/<str: slug>/bookmark/` for bookmarking and un-bookmarking a specific article then `api/bookmarks/` to fetch all bookmarks of a login user. This way you'll have no need for the serializers, plus it would help embed the "delete bookmark" feature within un-bookmarking.

**Review by llwasampijja — CHANGES_REQUESTED** [review]
Nice work @kalsmic, however as @AtamaZack  pointed out, the request body isn't really necessary. Since you can get an Article by id, you can pick the id from the URL!

**Comment by kalsmic** [comment]
> Awesome work @kalsmic, the logic is great, however, I believe it's better to have no request body. i.e let everything be in the url, e.g `api/articles/<str: slug>/bookmark/` for bookmarking and un-bookmarking a specific article then `api/bookmarks/` to fetch all bookmarks of a login user. This way you'll have no need for the serializers, plus it would help embed the "delete bookmark" feature within un-bookmarking.

Thanks, @AtamaZack, for this feedback, I have implemented it.

**Comment by kalsmic** [comment]
> This is good work @kalsmic. Though I noticed you have 3 endpoints - bookmarking an article, getting bookmarks, and deleting a bookmark. However, I think you can toggle bookmarking on and off using the same endpoint.

@bisonlou, we now have two endpoints, one endpoint to bookmark and un-bookmark and another endpoint to get the bookmarks

**Review by bisonlou — APPROVED** [review]

**Review by ZackAtama — APPROVED** [review]

**Review by llwasampijja — APPROVED** [review]

**Review by nadralia — APPROVED** [review]
Nice Work @kalsmic

**Pull request merged**
