### PR TITLE
#165273566 swagger api documentation

### PR DESCRIPTION
**Pull request by JamesMudidi**
#### What does this PR do?
Sets up Swagger API Documentation

#### Description of Tasks to be completed?
Added API documentation for the following endpoints

`Get /user/`
`Put /user/`
`Patch /user/`
`Post /users/`
`Post /users/login/`

#### How should this be manually tested?
After cloning the repository,

- Navigate into it and install the dependencies using `pip3 install -r requirements.txt`
- Run the application using `python3 manage.py runserver`
- Access the documentation by navigating to http://127.0.0.1:8000/docs/

#### Screenshots
Screenshot 2019-04-23 at 8 02 08 PM

#### What are the relevant pivotal tracker stories?
[165273566](https://www.pivotaltracker.com/story/show/165273566)

### CODE REVIEW

**Comment by kalsmic** [comment]
@JamesMudidi, nice work with the documentation, I also noticed to updated the login to only capture email and password and excluded the username as required.

**Review by nadralia — APPROVED** [review]
Nice Work , I like the idea of eliminating the username on the login response. Am not sure whether the status code for login response should be 201 , am thinking 200 would do

**Review by bisonlou — APPROVED** [review]
Tested this, and it works as defined. Well done.

**Comment by phillipseryazi** [comment]
@JamesMudidi you have 3 commits on your pr please squash them

**Comment by AtamaZack** [comment]
@JamesMudidi, all looks okay, however, please resolve the merge conflicts.

**Review by ZackAtama — CHANGES_REQUESTED** [review]
@JamesMudidi, all looks well, however, please resolve the merge conflicts.

**Pull request closed without merging**
