### PR TITLE
#165273569 Account activation

### PR DESCRIPTION
**Pull request by bisonlou**
#### What does this PR do?
- Implements account activation via email

#### Description of Task to be completed?
- Activate a users account on activation via email

#### How should this be manually tested?
In your environmental variables export the following with their values:
 - export EMAIL_HOST_PASSWORD=''
 - export EMAIL_HOST_USER=''

In An API Consumer for example Postman
Register a user with your email and password
You will receive a confirmation email with an activation link
Click the link and your account will be activated

#### What are the relevant pivotal tracker stories?
#165273569

### CODE REVIEW

**Comment by phillipseryazi** [comment]
@bisonlou please name your pr correctly, improve the coverage as well

**Review by llwasampijja — CHANGES_REQUESTED** [review]
@bisonlou , You have done a wonderful job. As @grey-felipe  has suggested, try to add tests for cases in case the user doesn't exist and in the case of an expired activation link!
Also as @JamesMudidi  suggested, you should squash the commits!

**Comment by kalsmic** [comment]
> @bisonlou, You have done a wonderful job. As @grey-felipe has suggested, try to add tests for cases in case the user doesn't exist and in the case of an expired activation link!
> Also as @JamesMudidi suggested, you should squash the commits!

@llwasampijja, it might be tricky at the moment to test for an expired activation link, much as it should expire after some time. Unlike when you use a token for such a scenario, setting an expiration in a byte string is indeed tricky. @llwasampijja, we might have to add this to the edge case and ensure that we work on it later afterwards. I am keeping track of the edge cases.

**Review by kalsmic — CHANGES_REQUESTED** [review]
@bisonlou, well done, as for the coverage, I agree with both @llwasampijja, more tests can be added to increase the coverage.

**Review by nadralia — COMMENTED** [review]
Nice Work @bisonlou , About the coverage ,Can you increase or ?

**Review by JamesMudidi — APPROVED** [review]
Apart from the coverage, all is good

**Review by ZackAtama — COMMENTED** [review]
Great work with the verification feature, only test coverage needed. Thank you @bisonlou

**Comment by bisonlou** [comment]
@llwasampijja @grey-felipe @AtamaZack @nadralia @JamesMudidi 
Your concern with the coverage has been duly noted. 
I have gone ahead and worked on it.
Please re-review the PR

**Review by kalsmic — APPROVED** [review]

**Review by llwasampijja — APPROVED** [review]

**Pull request merged**
