### PR TITLE
#165594492: unit tests for user retrieve update view

### PR DESCRIPTION
**Pull request by kalsmic**
#### What does this PR do?

- Adds unit tests for the retrieve and update user details
#### Description of the task to be completed?
Add tests for retrieving a user

#### How should this be manually tested?

- Run tests with the `pytest` command in the terminal to run

- Try updating a user with the following.

  1.  without a valid token.
  2.  without submitting valid request data.
  3.  with a username or email that belongs to another user.
  4.  with User a unique username or password.

#### Any background context you want to provide?
- Endpoint for retrieving a user GET `/api/user/`
- Endpoint for updating a user PUT  `/api/users/`

#### What are the relevant pivotal tracker stories

[#165594492](https://www.pivotaltracker.com/story/show/165594492)

### CODE REVIEW

**Review by JamesMudidi — APPROVED** [review]
Nice work on the 100% coverage Arthur

**Review by bisonlou — APPROVED** [review]
Great Job

**Review by nadralia — APPROVED** [review]
Nice Work, Every test check out

**Review by ZackAtama — COMMENTED** [review]
Great job @kalsmic

**Review by llwasampijja — COMMENTED** [review]
Nice work @kalsmic. Wouldn't docstrings be better than the comments?

**Comment by kalsmic** [comment]
> Nice work @kalsmic. Wouldn't docstrings be better than the comments?
@llwasampijja, I have used comments to explain lines of code within functions, Maybe as an example, you can clarify where in the code you are referring to.

**Pull request merged**
