### PR TITLE
#165273562 Database Setup

### PR DESCRIPTION
**Pull request by ZackAtama**
#### What does this PR do?
- Setup PostgreSQL as the default database engine for the application

#### Description of the task to be completed?
- Add psycopg2-binary as an application dependency to the requirements file
- Change default database engine from sqlite3 to PostgreSQL

#### How should this be manually tested?
- Clone the Github repository - `git clone https://github.com/andela/ah-backend-dojo.git`
- Navigate into the repository - `cd ah-backend-dojo`
- Create a virtual environment - `python3 -m venv [virtual_environment_name]`
- Activate the virtual environment - macOS: `source [virtual_environment_name]/bin/activate`
- Install the dependencies from the requirements file - `pip install -r requirements.txt`
-  Create a `.env` file, copy and paste in environment variables setup in the `.env_sample` file, in the blank quotes add your PostgreSQL database credentials.
- Make the migrations - `python manage.py makemigrations`
- Migrate - `python manage.py migrate`
- Run the server - `python manage.py runserver`

#### Any background context you want to provide?
The application was setup with sqlite3 as the default database engine, which has been changed to PostgreSQL

#### What are the relevant pivotal tracker stories
- [#165273562](https://www.pivotaltracker.com/story/show/165273562)

Reviewers
@kalsmic @bisonlou @nadralia  @llwasampijja @JamesMudidi

### CODE REVIEW

**Review by bisonlou — APPROVED** [review]
This looks good. Weldone @AtamaZack

**Review by JamesMudidi — APPROVED** [review]
Good job Zack

**Review by llwasampijja — APPROVED** [review]
Everything looks great!
Works as expected!

**Comment by nadralia** [comment]
Good work @AtamaZack , Am wondering are the different staging environment not helpful(production,development,Testing)?.

**Comment by kalsmic** [comment]
Well done @AtamaZack , the database was set up successfully.

**Comment by phillipseryazi** [comment]
@AtamaZack  resolve conflict on your branch

**Pull request merged**
