### PR TITLE
#165273576 Comment on an article

### PR DESCRIPTION
**Pull request by kalsmic**
#### What does this PR do?
- Adds functionality for adding a comment to an article and getting a list of comments attached to an article.
- Add unit tests for creating comments functionality
- Add unit tests for getting a list of comments functionality
- Add unit tests for updating a comment
-Add unit tests for deleting a comment
- Add unit tests for getting a specific comment

#### How should this be manually tested?
- Post Comment - ` POST https://ah-backend-dojo-dev.herokuapp.com/api/articles/title-rate/comments/`
Request body 
`
{
    "body": "my first comments"
}
`
- Get Comments list  - GET `https://ah-backend-dojo-dev.herokuapp.com/api/articles/title-rate/comments/`

- Get a specific Comment - GET `https://ah-backend-dojo-dev.herokuapp.com/api/articles/title-rate/comments/<comment_id>/`

- Update a Comment - PUT `https://ah-backend-dojo-dev.herokuapp.com/api/articles/title-rate/comments/<comment_id>/`

- Delete a Comment - DELETE `https://ah-backend-dojo-dev.herokuapp.com/api/articles/title-rate/comments/<comment_id>/`

#### Any background Context you want to provide
[Postman Collection](https://documenter.getpostman.com/view/5825796/S1LpZB7Z)

#### What are the relevant pivotal tracker stories?
[[#165273576]](https://www.pivotaltracker.com/story/show/165273576)

### CODE REVIEW

**Review by ZackAtama — CHANGES_REQUESTED** [review]
Great work @kalsmic , however, I believe if a user can create a comment, they should be able to delete it at their will.

**Review by nadralia — CHANGES_REQUESTED** [review]
Nice Work so far @kalsmic , however you forgot to add functionality for editing the comment. and also deleting comment as @AtamaZack identified

**Comment by kalsmic** [comment]
> Great work @kalsmic , however, I believe if a user can create a comment, they should be able to delete it at their will.

I am going to work on it

**Review by JamesMudidi — DISMISSED** [review]
@kalsmic, As @AtamaZack and @nadralia have pointed out, the comment feature should be flexible enough for the user to implement the Create, Update and Destroy functionalities. These features will help the user have more control on what they create on the application and it gives better user experience.

**Comment by kalsmic** [comment]
> Nice Work so far @kalsmic , however you forgot to add functionality for editing the comment. and also deleting comment as @AtamaZack identified

@nadralia, @AtamaZack, I have added update and delete for a comment.
I have also added an endpoint for getting a single comment

**Review by nadralia — APPROVED** [review]

**Review by nadralia — CHANGES_REQUESTED** [review]
@kalsmic Well done, we agreed to add the swagger documentation for each newly added endpoints, Add it and we are good to go with this.

**Review by ZackAtama — APPROVED** [review]

**Comment by kalsmic** [comment]
> @kalsmic Well done, we agreed to add the swagger documentation for each newly added endpoints, Add it and we are good to go with this.

@nadralia, we had agreed that the scrum master for the week would be working on the swagger documentation.

**Review by nadralia — APPROVED** [review]

**Review by bisonlou — APPROVED** [review]
Well done @kalsmic. This is well done.

**Comment by kalsmic** [comment]
> @kalsmic, As @AtamaZack and @nadralia have pointed out, the comment feature should be flexible enough for the user to implement the Create, Update and Destroy functionalities. These features will help the user have more control on what they create on the application and it gives better user experience.

@JamesMudidi, kindly review the PR again. I have implemented the features you requested.

**Review by llwasampijja — APPROVED** [review]
@kalsmic Great work, I have not discovered any errors! And all the feedback has been implemented!

**Pull request merged**
