### PR TITLE
#165273554 Write Unit Tests for Existing Features.

### PR DESCRIPTION
**Pull request by llwasampijja**
#### What does this PR do?
Add unit tests for the login feature
#### Description of Task to be completed?
* The task includes tests which make sure that the login endpoint responds as expected.
* This tests for a wrong password, wrong email, empty password, empty email, as well as a successful login.
#### How should this be manually tested?
This can be tested by running the unit tests using the pytest command, which is: 
`pytest`
#### Any background context you want to provide?
On local, the database migrations need to be up to date and the environment variables loaded.
#### What are the relevant pivotal tracker stories?
[#165273554](https://www.pivotaltracker.com/story/show/165273554)

### CODE REVIEW

**Review by JamesMudidi — APPROVED** [review]
Good work on the tests

**Review by nadralia — CHANGES_REQUESTED** [review]
Hi, @llwasampijja nice work there, can we also test for space in the username during registration and @kalsmic is also writing some tests and some checks that main break you tests especially the Password tests so i don't know how this will go. But i suggest you work together

**Review by ZackAtama — APPROVED** [review]
Awesome coverage with testing the existing features, however, after JWT authentication feature has been worked on, you will have to write the remaining tests for the `UserRetrieveUpdateAPIView(RetrieveUpdateAPIView)` class that's protected.

**Comment by llwasampijja** [comment]
> Hi, @llwasampijja nice work there, can we also test for space in the username during registration and @kalsmic is also writing some tests and some checks that main break you tests especially the Password tests so i don't know how this will go. But i suggest you work together

@nadralia thanks for the observation. I am going to change the passwords used in the unit tests so that they conform with the validations implemented by @kalsmic

**Review by nadralia — APPROVED** [review]

**Comment by kalsmic** [comment]
@nadralia, the login bug has been fixed.

**Pull request merged**
